### ISSUE TITLE
Keep reference to instance in Global Hooks

### ISSUE THREAD

**Issue by abusque** [belgoros/hello-javafx-maven#1]
Hi,

I've been working on a JavaFX project and I've used your repo as an example for Cucumber, JemmyFX, and Maven integration. However I was wondering whether there is a way to keep a reference to the instance of the class launched by the AppExecutor in beforeAll() from the GlobalHooks class.

Thanks.

**Comment by belgoros** [comment]
I don't really see the reason why you want to do that... No matter, you can use dependency injection and inject no matter which class just by passing it to the step definition class as an argument to its constructor. Hope this helps. Just add picocontainer dependency (or any other container) declaration to your POM file.

**Comment by abusque** [comment]
Alright thanks I'll look into picocontainer for that, until now I settled for a singleton approach which seems to do the job as well. The reason I need this is because I need to load different components into the application on the fly for testing purposes, and I need some sort of reference to the instance to do that in the way the application is designed.
